// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricetoolAPI.DataAccess;

#nullable disable

namespace PricetoolAPI.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231026170351_idgenerator")]
    partial class idgenerator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Corporate", b =>
                {
                    b.Property<int>("Cvr")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cvr");

                    b.ToTable("Corporates");

                    b.HasData(
                        new
                        {
                            Cvr = 41188917,
                            Address = "673 Dicki River, Cummingsstad, Dominica",
                            Id = 0,
                            Name = "Bednar, Mills and Padberg"
                        },
                        new
                        {
                            Cvr = 67090884,
                            Address = "90811 Rohan Villages, East Elliott, French Polynesia",
                            Id = 0,
                            Name = "Towne - Spencer"
                        },
                        new
                        {
                            Cvr = 35971657,
                            Address = "661 Aimee Freeway, Port Thea, United States of America",
                            Id = 0,
                            Name = "Herzog, Cremin and Tillman"
                        },
                        new
                        {
                            Cvr = 52920408,
                            Address = "19610 Heber Ranch, South Nick, Tunisia",
                            Id = 0,
                            Name = "Green, Adams and Rath"
                        },
                        new
                        {
                            Cvr = 19193614,
                            Address = "8870 Mikayla Springs, Terryhaven, Montenegro",
                            Id = 0,
                            Name = "Nienow Group"
                        },
                        new
                        {
                            Cvr = 86862377,
                            Address = "004 Kutch Mission, Port Larissamouth, Ireland",
                            Id = 0,
                            Name = "Feil, Ryan and Ruecker"
                        },
                        new
                        {
                            Cvr = 46336909,
                            Address = "234 Turcotte Center, Hintzview, San Marino",
                            Id = 0,
                            Name = "Graham, Trantow and Welch"
                        },
                        new
                        {
                            Cvr = 88997282,
                            Address = "812 Kenny Garden, New Daynafort, Canada",
                            Id = 0,
                            Name = "Macejkovic Inc"
                        },
                        new
                        {
                            Cvr = 64007232,
                            Address = "9650 Lily Union, Prosaccotown, China",
                            Id = 0,
                            Name = "Upton, D'Amore and Collins"
                        },
                        new
                        {
                            Cvr = 99423086,
                            Address = "69923 Lehner Forks, Baileyborough, Sri Lanka",
                            Id = 0,
                            Name = "Ankunding, Braun and Kutch"
                        });
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<int>("SubsidiaryCvr")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubsidiaryCvr");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Subsidiary", b =>
                {
                    b.Property<int>("Cvr")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentCorporateCvr")
                        .HasColumnType("int");

                    b.HasKey("Cvr");

                    b.HasIndex("ParentCorporateCvr");

                    b.ToTable("Subsidiary");

                    b.HasData(
                        new
                        {
                            Cvr = 59698292,
                            Address = "93203 Beier Forges, New Lambert, Germany",
                            Id = 0,
                            Name = "Stanton Group",
                            ParentCorporateCvr = 99423086
                        },
                        new
                        {
                            Cvr = 92296475,
                            Address = "3209 Kihn Prairie, North Viola, Lesotho",
                            Id = 0,
                            Name = "Hyatt, Stokes and Rohan",
                            ParentCorporateCvr = 52920408
                        },
                        new
                        {
                            Cvr = 65919724,
                            Address = "3660 Marquis Meadows, Zoiemouth, Bouvet Island (Bouvetoya)",
                            Id = 0,
                            Name = "Bernier, Haag and Barrows",
                            ParentCorporateCvr = 67090884
                        },
                        new
                        {
                            Cvr = 83892814,
                            Address = "0549 Vivianne Ferry, Croninbury, Brunei Darussalam",
                            Id = 0,
                            Name = "Orn, Jast and Bernhard",
                            ParentCorporateCvr = 41188917
                        },
                        new
                        {
                            Cvr = 93336309,
                            Address = "400 Luna Station, North Nathanielburgh, Jamaica",
                            Id = 0,
                            Name = "Jast, Wilkinson and Jacobson",
                            ParentCorporateCvr = 46336909
                        },
                        new
                        {
                            Cvr = 29972527,
                            Address = "3304 Jacobson Spring, East Clementfort, Turks and Caicos Islands",
                            Id = 0,
                            Name = "Jerde LLC",
                            ParentCorporateCvr = 86862377
                        },
                        new
                        {
                            Cvr = 55459288,
                            Address = "8669 Schimmel Parkways, Lake Isomburgh, Gambia",
                            Id = 0,
                            Name = "Reinger, Blanda and Bauch",
                            ParentCorporateCvr = 41188917
                        },
                        new
                        {
                            Cvr = 19665213,
                            Address = "5134 Camron Mall, West Marcelo, Tanzania",
                            Id = 0,
                            Name = "Jacobs, Boehm and Kreiger",
                            ParentCorporateCvr = 99423086
                        },
                        new
                        {
                            Cvr = 12552824,
                            Address = "796 Frami Lakes, Hickleland, Andorra",
                            Id = 0,
                            Name = "Rosenbaum, Walter and Sawayn",
                            ParentCorporateCvr = 88997282
                        },
                        new
                        {
                            Cvr = 54399873,
                            Address = "34260 Rolfson Club, Lake Clemensberg, Netherlands Antilles",
                            Id = 0,
                            Name = "Rippin - O'Hara",
                            ParentCorporateCvr = 64007232
                        });
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Product", b =>
                {
                    b.HasOne("PricetoolAPI.Domain.Entities.Subsidiary", "Subsidiary")
                        .WithMany("Products")
                        .HasForeignKey("SubsidiaryCvr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subsidiary");
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Subsidiary", b =>
                {
                    b.HasOne("PricetoolAPI.Domain.Entities.Corporate", "Corporate")
                        .WithMany("Subsidiaries")
                        .HasForeignKey("ParentCorporateCvr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corporate");
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Corporate", b =>
                {
                    b.Navigation("Subsidiaries");
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Subsidiary", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
