// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricetoolAPI.DataAccess;

#nullable disable

namespace PricetoolAPI.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Corporate", b =>
                {
                    b.Property<int>("Cvr")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cvr");

                    b.ToTable("Corporates");

                    b.HasData(
                        new
                        {
                            Cvr = 89733793,
                            Address = "2675 Welch Crescent, Moenfort, Swaziland",
                            Id = 0,
                            Name = "Kemmer LLC"
                        },
                        new
                        {
                            Cvr = 14439489,
                            Address = "64699 Kamren Islands, Mabelleborough, Mauritania",
                            Id = 0,
                            Name = "Littel, Schultz and Carroll"
                        },
                        new
                        {
                            Cvr = 70711494,
                            Address = "7612 Mante Camp, Reichelhaven, Saint Helena",
                            Id = 0,
                            Name = "Gibson, Abbott and Reynolds"
                        },
                        new
                        {
                            Cvr = 78740224,
                            Address = "829 Vanessa Squares, Isaiahstad, Bolivia",
                            Id = 0,
                            Name = "Metz LLC"
                        },
                        new
                        {
                            Cvr = 91592737,
                            Address = "7993 Cummerata Ranch, South Felton, Cuba",
                            Id = 0,
                            Name = "Murphy - Casper"
                        },
                        new
                        {
                            Cvr = 97686971,
                            Address = "861 Stamm Trail, East Nico, Australia",
                            Id = 0,
                            Name = "Hettinger Inc"
                        },
                        new
                        {
                            Cvr = 27871536,
                            Address = "28528 Daniela Roads, New Rosalindaborough, Jamaica",
                            Id = 0,
                            Name = "Torphy, Jacobi and McLaughlin"
                        },
                        new
                        {
                            Cvr = 35710475,
                            Address = "4422 Davonte Lake, North Keltonborough, Philippines",
                            Id = 0,
                            Name = "Hand, Bauch and Greenholt"
                        },
                        new
                        {
                            Cvr = 68075510,
                            Address = "7291 Rau Walks, New Jordaneberg, Central African Republic",
                            Id = 0,
                            Name = "Hamill, Douglas and Bergnaum"
                        },
                        new
                        {
                            Cvr = 59897910,
                            Address = "63950 Diamond Alley, New Arjun, Andorra",
                            Id = 0,
                            Name = "O'Conner, Zemlak and Herzog"
                        });
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<int>("SubsidiaryCvr")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubsidiaryCvr");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 60,
                            Name = "Practical Frozen Salad",
                            Principal = 9911.696248266970000m,
                            SubsidiaryCvr = 72347268,
                            Type = "Incredible"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Awesome Wooden Gloves",
                            Principal = 9890.429162391580000m,
                            SubsidiaryCvr = 60729582,
                            Type = "Ergonomic"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Sleek Plastic Salad",
                            Principal = 3801.109548321570000m,
                            SubsidiaryCvr = 17074996,
                            Type = "Fantastic"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Licensed Granite Computer",
                            Principal = 1493.716253703210000m,
                            SubsidiaryCvr = 30918898,
                            Type = "Small"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Handcrafted Wooden Hat",
                            Principal = 2203.463937814440000m,
                            SubsidiaryCvr = 91173819,
                            Type = "Gorgeous"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Practical Wooden Cheese",
                            Principal = 461.7082550304620000m,
                            SubsidiaryCvr = 87590755,
                            Type = "Awesome"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Unbranded Fresh Bacon",
                            Principal = 3365.204321099990000m,
                            SubsidiaryCvr = 60729582,
                            Type = "Handmade"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Handmade Metal Chips",
                            Principal = 7447.783491841160000m,
                            SubsidiaryCvr = 60729582,
                            Type = "Ergonomic"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Gorgeous Concrete Shirt",
                            Principal = 8872.024006907140000m,
                            SubsidiaryCvr = 60729582,
                            Type = "Small"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Gorgeous Cotton Hat",
                            Principal = 1375.491080924210000m,
                            SubsidiaryCvr = 24635605,
                            Type = "Sleek"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Tasty Fresh Table",
                            Principal = 5584.458392295560000m,
                            SubsidiaryCvr = 60729582,
                            Type = "Licensed"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Intelligent Metal Sausages",
                            Principal = 5319.42541295850000m,
                            SubsidiaryCvr = 64152329,
                            Type = "Fantastic"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Rustic Metal Fish",
                            Principal = 6226.400114628810000m,
                            SubsidiaryCvr = 97262314,
                            Type = "Refined"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Licensed Metal Chair",
                            Principal = 1932.197753752340000m,
                            SubsidiaryCvr = 87590755,
                            Type = "Handcrafted"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Tasty Metal Hat",
                            Principal = 3271.503882979860000m,
                            SubsidiaryCvr = 30918898,
                            Type = "Incredible"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Gorgeous Concrete Computer",
                            Principal = 470.2707225333950000m,
                            SubsidiaryCvr = 30918898,
                            Type = "Sleek"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Licensed Metal Towels",
                            Principal = 6839.88369291220000m,
                            SubsidiaryCvr = 60729582,
                            Type = "Sleek"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Handcrafted Plastic Fish",
                            Principal = 9259.340255794540000m,
                            SubsidiaryCvr = 64152329,
                            Type = "Awesome"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Refined Steel Fish",
                            Principal = 1317.239242025130000m,
                            SubsidiaryCvr = 97262314,
                            Type = "Tasty"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Incredible Soft Hat",
                            Principal = 7600.10268325080000m,
                            SubsidiaryCvr = 97262314,
                            Type = "Refined"
                        });
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Subsidiary", b =>
                {
                    b.Property<int>("Cvr")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentCorporateCvr")
                        .HasColumnType("int");

                    b.HasKey("Cvr");

                    b.HasIndex("ParentCorporateCvr");

                    b.ToTable("Subsidiary");

                    b.HasData(
                        new
                        {
                            Cvr = 25771257,
                            Address = "600 Cleora Squares, East Manuelaview, Bahamas",
                            Id = 0,
                            Name = "Ferry Inc",
                            ParentCorporateCvr = 70711494
                        },
                        new
                        {
                            Cvr = 30918898,
                            Address = "80689 Maegan Loop, Opheliachester, Tunisia",
                            Id = 0,
                            Name = "Batz, Gleichner and Kovacek",
                            ParentCorporateCvr = 70711494
                        },
                        new
                        {
                            Cvr = 60729582,
                            Address = "994 D'Amore Causeway, Hermistonmouth, Thailand",
                            Id = 0,
                            Name = "Bergstrom LLC",
                            ParentCorporateCvr = 78740224
                        },
                        new
                        {
                            Cvr = 97262314,
                            Address = "52041 Howell Street, Port Frankchester, Thailand",
                            Id = 0,
                            Name = "Schinner Inc",
                            ParentCorporateCvr = 27871536
                        },
                        new
                        {
                            Cvr = 72347268,
                            Address = "76677 Elton Parkways, Brannonview, Saudi Arabia",
                            Id = 0,
                            Name = "Dach, Kub and Pacocha",
                            ParentCorporateCvr = 59897910
                        },
                        new
                        {
                            Cvr = 17074996,
                            Address = "736 Alejandrin Glen, Cassinville, Mauritius",
                            Id = 0,
                            Name = "Brekke, Blanda and Wilderman",
                            ParentCorporateCvr = 89733793
                        },
                        new
                        {
                            Cvr = 24635605,
                            Address = "41538 Kozey Unions, Chandlerberg, Antarctica (the territory South of 60 deg S)",
                            Id = 0,
                            Name = "Kshlerin LLC",
                            ParentCorporateCvr = 78740224
                        },
                        new
                        {
                            Cvr = 64152329,
                            Address = "37737 Erna Throughway, Runolfsdottirton, Timor-Leste",
                            Id = 0,
                            Name = "Donnelly - Zemlak",
                            ParentCorporateCvr = 70711494
                        },
                        new
                        {
                            Cvr = 87590755,
                            Address = "6156 Jack Ford, Goldnerton, Pakistan",
                            Id = 0,
                            Name = "Runolfsson - Gutkowski",
                            ParentCorporateCvr = 35710475
                        },
                        new
                        {
                            Cvr = 91173819,
                            Address = "993 Alexys Fork, Waelchibury, Monaco",
                            Id = 0,
                            Name = "Wolff LLC",
                            ParentCorporateCvr = 97686971
                        });
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Product", b =>
                {
                    b.HasOne("PricetoolAPI.Domain.Entities.Subsidiary", "Subsidiary")
                        .WithMany("Products")
                        .HasForeignKey("SubsidiaryCvr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subsidiary");
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Subsidiary", b =>
                {
                    b.HasOne("PricetoolAPI.Domain.Entities.Corporate", "Corporate")
                        .WithMany("Subsidiaries")
                        .HasForeignKey("ParentCorporateCvr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corporate");
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Corporate", b =>
                {
                    b.Navigation("Subsidiaries");
                });

            modelBuilder.Entity("PricetoolAPI.Domain.Entities.Subsidiary", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
