//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pricetool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pricetool.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        internal static string Label1 {
            get {
                return ResourceManager.GetString("Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde.
        /// </summary>
        internal static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hovedstol/max.
        /// </summary>
        internal static string Label3 {
            get {
                return ResourceManager.GetString("Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engagement.
        /// </summary>
        internal static string Label4 {
            get {
                return ResourceManager.GetString("Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seneste beregning.
        /// </summary>
        internal static string Label5 {
            get {
                return ResourceManager.GetString("Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilføjet af.
        /// </summary>
        internal static string Label6 {
            get {
                return ResourceManager.GetString("Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Påvirker.
        /// </summary>
        internal static string Label7 {
            get {
                return ResourceManager.GetString("Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ret/ Slet.
        /// </summary>
        internal static string Label8 {
            get {
                return ResourceManager.GetString("Label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RET.
        /// </summary>
        internal static string ValueforLabel8 {
            get {
                return ResourceManager.GetString("ValueforLabel8", resourceCulture);
            }
        }
    }
}
